### ISSUE TITLE
d correction

### ISSUE THREAD

**Issue by luigielbambino** [urjhams/Image-Analysis-AS-3-2018#4]
function [H,theta_range,p_range] = hough_Detection(bw)
  [w, h] = size(bw);
  pMax = ceil(sqrt(w.^2 + h.^2));
  theta_range = -90:89;
  p_range = -pMax:pMax;
  H = zeros(2 * pMax + 1, length(theta_range));

  for x = 1:w
    for y = 1:h
      if bw(x,y) ~= 0
        for thetaIndex = 1:length(theta_range)
          p = x * cos(theta_range(thetaIndex) + pi/180) + y * sin(theta_range(thetaIndex) + pi/180);
          pIndex = round(p + pMax) + 1;
          H(pIndex,thetaIndex) = H(pIndex,thetaIndex) + 1;
        end
      end
    end
  end
end

**Comment by urjhams** [comment]
corrected

**Comment by luigielbambino** [comment]
plot(thetas(peaks(:, 2)), P(peaks(:, 1)), 's', 'color', 'blue');

**Comment by luigielbambino** [comment]
figure, imshow(grayScale),title('Hough Line'); hold on
     max_len = 0;
     for k = 1:length(lines)
         xy = [lines(k).point1; lines(k).point2];
         plot(xy(:,1),xy(:,2),'LineWidth',2,'Color','green');
         % Plot beginnings and ends of lines
         plot(xy(1,1),xy(1,2),'x','LineWidth',2,'Color','yellow');
         plot(xy(2,1),xy(2,2),'x','LineWidth',2,'Color','red');
         len = norm(lines(k).point1 - lines(k).point2);
         if ( len > max_len)
             max_len = len;
             xy_long = xy;
         end
     end
    plot(xy_long(:,1),xy_long(:,2),'LineWidth',2,'Color','cyan');

**Comment by urjhams** [comment]
function [H, theta, rho] = hough_lines_acc(BW)
  theta = linspace(-90, 89, 180);
  dMax = sqrt((size(BW,1)) ^ 2 + (size(BW,2)) ^ 2);
  diagonal = ceil(dMax);% rho ranges from -diagonal to diagonal
  rho = -diagonal : diagonal;
  numRho = 2 * ceil(dMax);
  numTheta = length(theta);
  H = zeros(numRho, numTheta);
  for i = 1 : size(BW,1)
    for j = 1 : size(BW,2)
      if (BW(i, j))
        for k = 1 : numTheta
          temp = j * cos(theta(k) * pi / 180) + i * sin(theta(k) * pi / 180); % Convert radiance to degree
          rowIndex = round(temp + diagonal) + 1;
          H(rowIndex, k) = H(rowIndex, k) + 1;
        end
      end
    end
  end
  %disp(H)
end

%for comparing

**Comment by luigielbambino** [comment]
function [H,theta_range,p_range] = hough_Detection(bw)
  [w, h] = size(bw);
  pMax = ceil(sqrt(w^2 + h^2));
  theta_range = -90:89;
  p_range = -pMax:pMax;
  H = zeros(2 * pMax, length(theta_range));
  length(p_range)
  for x = 1:w
    for y = 1:h
      if bw(x,y)
        for thetaIndex = 1:length(theta_range)
          p = round(x * cos(theta_range(thetaIndex) * pi/180) + y * sin(theta_range(thetaIndex) * pi/180));
          pIndex = round(p + pMax) + 1;
          H(pIndex,thetaIndex) = H(pIndex,thetaIndex) + 1;
        end
      end
    end
  end
end

**Comment by urjhams** [comment]
function [H, theta_range, rho] = hough_lines_acc(BW)
  theta_range = linspace(-90, 89, 180);
  dMax = ceil(sqrt((size(BW,1)) ^ 2 + (size(BW,2)) ^ 2));
  rho = -dMax : dMax;
  H = zeros(2 * dMax, length(theta_range));
  for i = 1 : size(BW,1)
    for j = 1 : size(BW,2)
      if (BW(i, j))
        for thetaIndex = 1 : length(theta_range)
          p = j * cos(theta_range(thetaIndex) * pi / 180) + i * sin(theta_range(thetaIndex) * pi / 180); % Convert radiance to degree
          pIndex = round(p + dMax) + 1;
          H(pIndex, thetaIndex) = H(pIndex, thetaIndex) + 1;
        end
      end
    end
  end
end

**Comment by urjhams** [comment]
function [H,theta_range,p_range] = hough_Detection(bw)
  [w, h] = size(bw);
  theta_range = -90 : 89;
  pMax = ceil(sqrt(w ^ 2 + h ^ 2));
  p_range = -pMax:pMax;
  H = zeros(2 * pMax, length(theta_range));
  for x = 1 : w
    for y = 1 : h
      if (bw(x,y))
        for thetaIndex = 1 : length(theta_range)
          p = x * cos(theta_range(thetaIndex) * pi / 180) + y * sin(theta_range(thetaIndex) * pi / 180);
          pIndex = round(p + pMax) + 1;
          H(pIndex,thetaIndex) = H(pIndex,thetaIndex) + 1;
        end
      end
    end
  end
end

**Comment by luigielbambino** [comment]
function [H, theta_range, rho] = hough_Detection(bw)
 [w, h] = size(bw);
 theta_range = -90:89;
 dMax = ceil(sqrt(w ^ 2 + h ^ 2));
 rho = -dMax : dMax;
 H = zeros(2 * dMax, length(theta_range));
 for x = 1 : w
 for y = 1 : h
 if (bw(x, y))
 for thetaIndex = 1 : length(theta_range)
 p = y * cos(theta_range(thetaIndex) * pi / 180) + x * sin(theta_range(thetaIndex) * pi / 180);
 pIndex = round(p + dMax) + 1;
 H(pIndex, thetaIndex) = H(pIndex, thetaIndex) + 1;
 end
 end
 end
 end
 end
